# Generated by Django 4.2.6 on 2023-11-23 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendaMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AlterField(
            model_name='referendum',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 18, 46, 44, 214217, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 18, 46, 44, 215319, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 18, 46, 44, 213081, tzinfo=datetime.timezone.utc)),
        ),
    ]
