# Generated by Django 4.2.6 on 2023-11-04 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('referendaMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Referendum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 54, 50, 93661, tzinfo=datetime.timezone.utc))),
                ('date_available', models.DateTimeField(null=True)),
                ('date_expired', models.DateTimeField(null=True)),
                ('choices', models.ManyToManyField(blank=True, to='referendaMain.choice')),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 54, 50, 92128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 54, 50, 95478, tzinfo=datetime.timezone.utc))),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referendaMain.choice')),
                ('referendum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='referendaMain.referendum')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referendaMain.voter')),
            ],
        ),
    ]
