# Generated by Django 4.2.6 on 2023-11-23 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendaMain', '0002_alter_user_managers_remove_user_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referendum',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 18, 50, 4, 699775, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 18, 50, 4, 700776, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 18, 50, 4, 698690, tzinfo=datetime.timezone.utc)),
        ),
    ]
