# Generated by Django 4.2.6 on 2023-11-04 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendaMain', '0002_choice_referendum_alter_voter_date_created_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referendum',
            name='date_expired',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 20, 58, 29, 228560, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 20, 58, 29, 229544, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 20, 58, 29, 227383, tzinfo=datetime.timezone.utc)),
        ),
    ]
