# Generated by Django 4.2.6 on 2023-11-23 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendaMain', '0003_alter_referendum_date_published_alter_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referendum',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 18, 56, 11, 27306, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 18, 56, 11, 28307, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 18, 56, 11, 26182, tzinfo=datetime.timezone.utc)),
        ),
    ]
