# Generated by Django 4.2.6 on 2023-11-23 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendaMain', '0004_alter_referendum_date_published_alter_vote_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referendum',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 19, 0, 35, 170593, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 19, 0, 35, 171601, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 19, 0, 35, 169502, tzinfo=datetime.timezone.utc)),
        ),
    ]
