# Generated by Django 4.2.6 on 2023-11-06 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendaMain', '0004_alter_referendum_date_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2023, 11, 6, 13, 3, 29, 149070, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 13, 3, 29, 150006, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 13, 3, 29, 147946, tzinfo=datetime.timezone.utc)),
        ),
    ]
